# Generated by Django 2.0 on 2018-10-17 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdetail',
            name='date_init',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
