# Generated by Django 2.0 on 2018-10-17 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0004_auto_20181017_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdetail',
            name='date_yesterday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
