# Generated by Django 2.0 on 2018-10-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0005_readdetail_date_yesterday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='date_new',
        ),
        migrations.RemoveField(
            model_name='readdetail',
            name='date_yesterday',
        ),
    ]
