# Generated by Django 2.0 on 2018-10-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181009_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readtime',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadTime',
        ),
    ]
